### ISSUE TITLE
[REQ] Support for map images directly from GameTracker

### ISSUE THREAD

**Issue by crashzk** [TianxSky/DiscordStatus#1]
Would it be possible to implement that for the game map images it uses the GameTracker link directly?

https://image.gametracker.com/images/maps/160x120/csgo/de_mirage.jpg
https://image.gametracker.com/images/maps/160x120/csgo/de_dust2.jpg
https://image.gametracker.com/images/maps/160x120/csgo/de_vertigo.jpg
https://image.gametracker.com/images/maps/160x120/csgo/de_inferno.jpg

SourceMod/CSGO already had something like this:
https://github.com/Bara/Discord-MapNotification/blob/c1a684db16884574846b2e4175a28d13ea72b2e8/scripting/discord_MapNotification.sp#L141C5-L144

**Comment by TianxSky** [comment]
it is supported, just replace map name with {MAPNAME} in the MapImg config

**Comment by crashzk** [comment]
@Tian7777 I tested it as follows:

```
  "MapImg": "https://image.gametracker.com/images/maps/160x120/csgo/{MAPNAME}.jpg",
 ```
It didn't work, it doesn't show the map image.
![image](https://github.com/Tian7777/DiscordStatus/assets/32937653/55c4f526-6ea1-4e91-96da-46145454dfd5)
