### ISSUE TITLE
[REQ] Support for translating message sentences

### ISSUE THREAD

**Issue by crashzk** [TianxSky/DiscordStatus#3]
Would it be possible to add support so that we can translate the `👈 Join Here` and `Server Empty` messages from the webhook:

![image](https://github.com/Tian7777/DiscordStatus/assets/32937653/44643a0f-e17b-4f22-b88e-205ff60e8a90)
![image](https://github.com/Tian7777/DiscordStatus/assets/32937653/27152bc6-2267-4b58-9e98-1a25ef99cc39)
![image](https://github.com/Tian7777/DiscordStatus/assets/32937653/b7d93a85-873c-4117-9c92-595d0b52a510)

**Comment by TianxSky** [comment]
will add
next update

**Comment by TianxSky** [comment]
Added
